version: 2.1

base_filters: &base_filters
  tags:
    only: /.*/
  branches:
    ignore: [new-screenshots, screenshots, metadata]

release_ios_filters: &release_ios_filters
  tags:
    only: /^v[1-9]+\.[0-9]+\.[0-9]+-rc.*/
  branches:
    ignore: /.*/

release_mac_filters: &release_mac_filters
  tags:
    only: /^v[1-9]+\.[0-9]+\.[0-9]+-mac-rc.*/
  branches:
    ignore: /.*/

orbs:
  swiftlint: ngs/swiftlint@0.0.1
  danger: ngs/danger@0.0.1
  fastlane: ngs/fastlane@0.0.4

commands:
  setup:
    steps:
      - checkout
      - fastlane/bundle-install
      - restore_cache:
          keys:
            - v2-spm-{{ checksum "CI2Go.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}
            - v2-spm
      - run:
          name: Resolve Swift Package Dependencies
          command: xcodebuild -resolvePackageDependencies -scheme CI2Go -project CI2Go.xcodeproj -derivedDataPath $DERIVED_DATA_PATH
      - save_cache:
          key: v2-spm-{{ checksum "CI2Go.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}
          paths:
            - DerivedData/SourcePackages

jobs:
  build:
    executor: fastlane/macos
    environment:
      DERIVED_DATA_PATH: DerivedData
      GYM_CLONED_SOURCE_PACKAGES_PATH: DerivedData/SourcePackages
      MATCH_READONLY: 'true'
      FASTLANE_SKIP_UPDATE_CHECK: 1
    parameters:
      target:
        type: enum
        enum: [beta, release]
      platform:
        type: enum
        enum: [ios, mac]
    steps:
      - setup
      - run:
          name: 'Copy Mac Catalyst Provisioning Profiles'
          command: /bin/bash -c .circleci/copy-provisioning-profiles.sh
      - fastlane/lane:
          command: ios << parameters.target >>_match
      - fastlane/lane:
          command: mac << parameters.target >>_match
      - fastlane/lane:
          command: set_build_number
      - fastlane/lane:
          command: << parameters.platform >> << parameters.target >>_build
      - run:
          name: Send dSYM to Firebase Crashlytics
          command: ./Vendor/Firebase/FirebaseCrashlytics/upload-symbols -gsp CI2Go/GoogleService-Info.plist -p ios build/<< parameters.target >>/CI2Go.app.dSYM.zip
      - store_artifacts:
          path: build
          destination: build
      - store_artifacts:
          path: ~/Library/Logs/gym
          destination: logs/gym
      - persist_to_workspace:
          root: build
          paths: [<< parameters.target >>]

  upload:
    executor: fastlane/macos
    environment:
      DERIVED_DATA_PATH: DerivedData
      GYM_CLONED_SOURCE_PACKAGES_PATH: DerivedData/SourcePackages
      MATCH_READONLY: 'true'
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      FASTLANE_SKIP_UPDATE_CHECK: 1
    parameters:
      target:
        type: enum
        enum: [beta, release]
      platform:
        type: enum
        enum: [ios, mac]
    steps:
      - checkout
      - attach_workspace:
          at: build
      - fastlane/bundle-install
      - fastlane/lane:
          command: << parameters.platform >> << parameters.target >>_upload

  tests:
    executor: fastlane/macos
    environment:
      DERIVED_DATA_PATH: DerivedData
      SCAN_CLONED_SOURCE_PACKAGES_PATH: DerivedData/SourcePackages
      MATCH_READONLY: 'true'
      FASTLANE_SKIP_UPDATE_CHECK: 1
    steps:
      - setup
      - fastlane/lane:
          command: tests
      #- fastlane:
      #   command: send_coveralls
      - store_test_results:
          path: fastlane/test_output
      - store_artifacts:
          path: fastlane/test_output
          destination: test_output
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: logs/scan

  screenshots:
    executor: fastlane/macos
    environment:
      DERIVED_DATA_PATH: DerivedData
      GYM_CLONED_SOURCE_PACKAGES_PATH: DerivedData/SourcePackages
      MATCH_READONLY: 'true'
      FASTLANE_SKIP_UPDATE_CHECK: 1
    steps:
      - setup
      - run: 'bundle exec fastlane screenshots | egrep -v $UI_TEST_CIRCLE_TOKEN'
      - persist_to_workspace:
          root: fastlane
          paths: [screenshots]
      - store_artifacts:
          path: fastlane/screenshots
          destination: screenshots
      - store_artifacts:
          path: ~/Library/Logs/snapshot
          destination: logs/snapshot

workflows:
  app:
    jobs:
      - swiftlint/run:
          name: swiftlint
          filters:
            <<: *base_filters

      - danger/run:
          name: danger
          filters:
            <<: *base_filters

      - tests:
          requires: [swiftlint, danger]
          filters:
            <<: *base_filters

      - screenshots:
          filters:
            branches:
              only: new-screenshots

      - build:
          name: beta_build
          target: beta
          platform: ios
          requires: [tests]
          filters:
            <<: *base_filters

      - build:
          name: beta_build_mac
          target: beta
          platform: mac
          requires: [tests]
          filters:
            <<: *base_filters

      - upload:
          name: beta_upload
          target: beta
          platform: ios
          requires: [beta_build]
          filters:
            <<: *base_filters

      - build:
          name: release_build
          target: release
          platform: ios
          requires: [tests]
          filters:
            <<: *release_ios_filters

      - build:
          name: release_build_mac
          target: release
          platform: mac
          requires: [tests]
          filters:
            <<: *release_mac_filters

      - upload:
          name: release_upload
          target: release
          platform: ios
          requires: [release_build]
          filters:
            <<: *release_ios_filters

      - upload:
          name: release_upload_mac
          target: release
          platform: mac
          requires: [release_build_mac]
          filters:
            <<: *release_mac_filters

      - fastlane/lane:
          name: release_metadata
          command: ios release_metadata
          filters:
            <<: *release_mac_filters

      - fastlane/lane:
          name: release_metadata_mac
          command: mac release_metadata
          filters:
            <<: *release_mac_filters

      - fastlane/lane:
          name: ios release_screenshots
          command: release_screenshots
          filters:
            branches:
              only: screenshots

      - fastlane/lane:
          name: mac release_screenshots
          command: release_screenshots
          filters:
            branches:
              only: screenshots
