version: 2.1

orbs:
  swiftlint: ngs/swiftlint@0.0.1
  danger: ngs/danger@0.0.1
  fastlane: ngs/fastlane@0.0.4

commands:
  setup:
    steps:
      - checkout
      - fastlane/bundle-install

jobs:
  build:
    executor: fastlane/macos
    environment:
      DERIVED_DATA_PATH: DerivedData
    parameters:
      target:
        type: enum
        enum: [beta, release]
      platform:
        type: enum
        enum: [ios, mac]
    steps:
      - setup
      - run:
          name: 'Copy Mac Catalyst Provisioning Profiles'
          command: /bin/bash -c .circleci/copy-provisioning-profiles.sh
      - fastlane/lane:
          command: ios << parameters.target >>_match
      - fastlane/lane:
          command: mac << parameters.target >>_match
      - fastlane/lane:
          command: set_build_number
      - fastlane/lane:
          command: << parameters.platform >> << parameters.target >>_build
      - store_artifacts:
          path: build
          destination: build
      - store_artifacts:
          path: ~/Library/Logs/gym
          destination: logs/gym
      - persist_to_workspace:
          root: build
          paths: [<< parameters.target >>]

  upload:
    executor: fastlane/macos
    environment:
      DERIVED_DATA_PATH: DerivedData
    parameters:
      target:
        type: enum
        enum: [beta, release]
      platform:
        type: enum
        enum: [ios, mac]
    steps:
      - checkout
      - attach_workspace:
          at: build
      - fastlane/bundle-install
      - fastlane/lane:
          command: << parameters.platform >> << parameters.target >>_upload

  tests:
    executor: fastlane/macos
    environment:
      DERIVED_DATA_PATH: DerivedData
    steps:
      - setup
      - fastlane/lane:
          command: tests
      #- fastlane:
      #   command: send_coveralls
      - store_test_results:
          path: fastlane/test_output
      - store_artifacts:
          path: fastlane/test_output
          destination: test_output
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: logs/scan

  screenshots:
    executor: fastlane/macos
    environment:
      DERIVED_DATA_PATH: DerivedData
    steps:
      - setup
      - run: 'bundle exec fastlane screenshots | egrep -v $UI_TEST_CIRCLE_TOKEN'
      - persist_to_workspace:
          root: fastlane
          paths: [screenshots]
      - store_artifacts:
          path: fastlane/screenshots
          destination: screenshots
      - store_artifacts:
          path: ~/Library/Logs/snapshot
          destination: logs/snapshot

workflows:
  app:
    jobs:
      - swiftlint/run:
          name: swiftlint
          filters:
            branches:
              ignore: [new-screenshots, screenshots, metadata]

      - danger/run:
          name: danger
          filters:
            branches:
              ignore: [new-screenshots, screenshots, metadata]

      - tests:
          requires: [swiftlint, danger]
          filters:
            branches:
              ignore: [new-screenshot, sscreenshots, metadata]

      - screenshots:
          filters:
            branches:
              only: new-screenshots

      - build:
          name: beta_build
          target: beta
          platform: ios
          requires: [tests]

      - build:
          name: beta_build_mac
          target: beta
          platform: mac
          requires: [tests]

      - upload:
          name: beta_upload
          target: beta
          platform: ios
          requires: [beta_build]
          filters:
            branches:
              only: [develop]

      - build:
          name: release_build
          target: release
          platform: ios
          requires: [tests]
          filters:
            branches:
              only: [/release-.+/]

      - build:
          name: release_build_mac
          target: release
          platform: mac
          requires: [tests]
          filters:
            branches:
              only: [/release-.+/]

      - upload:
          name: release_upload
          target: release
          platform: ios
          requires: [release_build]
          filters:
            branches:
              ignore: metadata

      - upload:
          name: release_upload_mac
          target: release
          platform: mac
          requires: [release_build_mac]
          filters:
            branches:
              ignore: metadata

      - fastlane/lane:
          name: release_metadata
          command: ios release_metadata
          filters:
            branches:
              only: [/release-.+/, metadata]

      - fastlane/lane:
          name: release_metadata_mac
          command: mac release_metadata
          filters:
            branches:
              only: [/release-.+/, metadata]

      - fastlane/lane:
          name: ios release_screenshots
          command: release_screenshots
          filters:
            branches:
              only: screenshots

      - fastlane/lane:
          name: mac release_screenshots
          command: release_screenshots
          filters:
            branches:
              only: screenshots
